# https://taskfile.dev

version: '3'

vars:
  #GREETING: Hello, World! # use with "{{GREETING}}" in a command

tasks:
  default:
    cmds:
      - clojure -M -m clj-tumblr-summarizer.main
    silent: false
