name: Archive latest Tumblr posts
on:
  #schedule:
  #  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
          distribution: 'zulu'
          java-version: 11
    - uses: DeLaGuardo/setup-clojure@3.2
      with:
          cli: 1.10.1.693
    - name: Configure AWS Credentials
    # See https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#permissions-for-assuming-a-role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    # FIXME: Get info about the latest backed up post
    - name: Make api-key available to the app
      run: |
        echo -n "$TUMBLR_API_KEY" > .api-key
        mkdir data
      env:
        TUMBLR_API_KEY: ${{ secrets.TUMBLR_API_KEY }}
    - name: Get latest timestamp from S3 # FIXME Make it not fail if fixe not exists
      run: aws s3 cp "s3://$BUCKET/max-timestamp"  ./data/max-timestamp
      env:
        BUCKET: ${{ secrets.BUCKET }}
    - name: Archive new posts # NOTE: Requires the secrets in the env
      run: clojure -M -m clj-tumblr-summarizer.main
      # FIXME !!! Fails with 'URISyntaxException: Illegal character in query at index 122: http://api.tumblr.com/v2/blog/holyjak.tumblr.com/posts?npf=true&api_key=***'
    - name: Upload to S3
      run: aws s3 sync ./data "s3://$BUCKET"
      env:
        BUCKET: ${{ secrets.BUCKET }}
    